### ISSUE TITLE
No such file or directory 'best_state.json'

### ISSUE THREAD

**Issue by yikeda0124** [Xingyu-Lin/VCD#2]
I've tried VCD planning with a pre-trained model, but I got an error.
```
Traceback (most recent call last):
  File "VCD/main_plan.py", line 383, in <module>
    main(get_default_args())
  File "VCD/main_plan.py", line 189, in main
    vcd_edge = load_edge_model(args.edge_model_path, env)
  File "VCD/main_plan.py", line 125, in load_edge_model
    edge_model_vv = json.load(open(osp.join(edge_model_dir, 'best_state.json')))
FileNotFoundError: [Errno 2] No such file or directory: './pretrained/best_state.json'
```
Where can I find the best_state.json? Thank you.

**Comment by yufeiwang63** [comment]
sorry, we forgot to include such files in our google drive. They can be downloaded via this [google drive link](https://drive.google.com/drive/folders/1CdCodTJ65NGK2qMK0wjsaOp_Ra6sTmD7?usp=sharing)

**Comment by yufeiwang63** [comment]
fixed by uploading the json files via google drive
